name: Java Maven Build & Publish Artifact

on:
    push:
        branches:
          - main
          - master
          - develop
          - feature/*
          - dev
    pull_request: null
    workflow_dispatch: null

permissions:
    contents: read
    actions: read
    checks: write
    
jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
            name: Maven Tests
            path: target/surefire-reports/*.xml
            reporter: java-junit
            fail-on-error: true

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
